name: Deploy PWA with Auto Update

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Update PWA version
      run: npm run update-pwa
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to Firebase/Netlify/Vercel
      run: |
        # Add your deployment commands here
        # For Firebase: npm install -g firebase-tools && firebase deploy
        # For Netlify: npm install -g netlify-cli && netlify deploy --prod --dir=dist
        # For Vercel: npm install -g vercel && vercel --prod
        echo "Add your deployment commands here"
        
    - name: Commit version update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/sw.js package.json
        git diff --staged --quiet || git commit -m "🚀 Auto-update PWA version [skip ci]"
        git push
